<?php

namespace Pmovil\Ipx\OnlineLoockup;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-06 at 15:11:30.
 */
class OnlineLookupApiServiceTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var OnlineLookupApiService
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new OnlineLookupApiService();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Pmovil\Ipx\OnlineLoockup\OnlineLookupApiService::resolveClientIP
     */
    public function testResolveClientIP() {
        $request = new ResolveClientIPRequest($correlationId, $clientIPAddress, $campaignName, $username, $password);
        $resp = $this->object->resolveClientIP($request);
        print_r($resp);
    }

}
